version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-ecr: circleci/aws-ecr@6.7.0
  docker: circleci/docker@1.5.0
  python-lint: qventus/python-lint@0.0.6
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.4.0

workflows:
  linting_dockerfile:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
  lint:
    jobs:
      - python-lint/lint:
          working-directory: .
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: microservice
          tag: "$CIRCLE_BUILD_NUM"
